### ISSUE TITLE
Subscription selection not working

### ISSUE THREAD

**Issue by ffreville** [microsoft/spring-cloud-azure#532]
I'm trying to connect to my eventHub and i'm facing an issue because i have two subscriptions.
In my azure authentication file, i have "subscriptionId": "11111111-1111-1111-1111-111111111111"
but when i launched my spring boot application, the eventHub is searched in the subscription "22222222-2222-2222-2222-222222222222".

Is it a bug ? Do you have an idea on how i can fix this ? 

Thanks

**Comment by dsibilio** [comment]
That's odd. Maybe the azure auth file was generated for subscription Id 22222222-2222-2222-2222-222222222222 and someone changed the subscriptionId inside to 11111111-1111-1111-1111-111111111111. If that's the case, I don't think that change would suffice.

You'd have to regenerate the azure authentication file as shown [here](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub#create-an-azure-credential-file).
Make sure to run the `az account set -s 11111111-1111-1111-1111-111111111111` command with the correct subscription Id before running `az ad sp create-for-rbac --sdk-auth > my.azureauth`.

**Comment by warrenzhu25** [comment]
I suppose you want to use different resources on different subscription. Some suggestions here:
1. If you want to use multiple azure resources together, it's better to put then under the same subscription.
2. If you still want to use different subscription, then you should prefer connection string based usage since credential file only have one subscription inside. Using credential file might cause issues

**Comment by warrenzhu25** [comment]
I might close this. If you still have issue, please free to reopen.
