### ISSUE TITLE
Unable to run the EventHubs Kafka sample 

### ISSUE THREAD

**Issue by rasavant-ms** [microsoft/spring-cloud-azure#603]
## Expected Behavior
EventHub Kafka sample works when run after following instructions in README

## Current Behavior
Compilation issues seen when running mvn clean package

## Possible Solution
Adding correct dependencies in pom.xml file

## Steps to Reproduce (for bugs)
* Follow README.md instructions

## Branch
* master

## Your Environment
* Version used: Apache Maven 3.6.1 Java version 11
* Operating System and version (desktop or mobile): "windows 10", version: "10.0", arch: "amd64"

**Comment by saragluna** [comment]
Thanks for reaching out. Could you please offer more details, such as which version your project is targeted on, the compilation error?

**Comment by rasavant-ms** [comment]
@saragluna - Sorry I did not keep a track of the compilation error as I worked towards fixing it and have submitted a PR #604 
The project was targeted to use Apache Maven 3.6.1 Java version 11

**Comment by saragluna** [comment]
I closed the PR because it tries to specify a fixed version, however, we keep upgrading the version whenever we make a release. I think we could try run `mvn clean package` from https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples this folder to see whether it could solve the compilation issue.

**Comment by saragluna** [comment]
Closing this issue.
