### ISSUE TITLE
Enhancement: when we have app config and application.yaml in application, can we set the priority to application.yaml?

### ISSUE THREAD

**Issue by Karthickramk** [microsoft/spring-cloud-azure#695]
## Expected Behavior
* We have both application.yaml and app config enabled.
* Some developers want to override this property in their local environment and use it. Because overriding in the app config because that will impact the whole team. But when they do it, app config property is taking the precedence. As a workaround each developer is duplicating the property with the new label and using that label in the app config bootstrap file. 
* is there a way we can achieve this some configuration so that application.yaml will take precedence?

## Current Behaviour
* If there is duplicate key in application.yaml and app config, the app config is taking the precedence.

## Possible Solution
* expose some config so that application.yaml will take precedence.

## Your Environment
* Version used: 1.2.5
* Operating System and version (desktop or mobile): Java 11 
* SDK version: 1.2.5

**Comment by mrm9084** [comment]
@Karthickramk I am unsure of a way to do this. The issue comes from spring-cloud-azure-appconfiguraiton-config loading in the Spring Boot process. The best work around I can give at the moment is instead of each developer creating there own label have 1 label for all developers. Then instead of putting a value in the configuration put a placeholder i.e. ${another.configuration}

**Comment by mrm9084** [comment]
@Karthickramk  I will look into this more to see if there is anything else that can be done about this.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
